---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - cmake
    - mono-complete
    - npm
    - python3-pip
    - powerline
    - fonts-powerline
    - vim
    - tmux
    - zsh

- name: install oh-my-zsh
  shell: sh -c "$(wget -0- {{ zsh_url }}"

- name: set zsh as default shell
  shell: chsh -s $(which zsh)

- name: clone zsh syntax highlighting repo
  git: 'https://github.com/zsh-users/zsh-syntax-highlighting.git "$HOME/.zsh-syntax-highlighting"'
  depth: 1
  dest: /home/"{{ ansible_user }}"
